# Use the latest Alpine Linux image as the base
FROM alpine:3.20

# Update the package lists
RUN apk update

# Install the PHP 8.3 development packages
RUN apk add --no-cache \
    bash
    unzip
    php83
    php83-bcmath
    php83-bz2
    php83-cli
    php83-common
    php83-dev
    php83-intl
    php83-json
    php83-phar
    php83-session
    php83-xdebug
    php83-zip
    php-json
    php-pear
    && rm -rf /var/cache/apk/* # buildkit

# Set the working directory
WORKDIR /php/app

# Copy the application code
COPY . .

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install PHP dependencies
RUN composer install --optimize-autoloader

# Start Apache
CMD ["php", "index.php"]
